[package]
name = "the_lonely_terminal"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
default = []
nocon = [] # No console window

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
codegen-units = 1

[dependencies]
macroquad = { version = "0.4.14", features = ["audio"] }

[build-dependencies]
static_vcruntime = "3.0.0"
